position:
  level: L3
  act: 2
  chapter: null
  scene: null

mode: manual

canon_version: 2
last_commit_hash: 7a62d21

max_context_tokens: 100000

context_manifest:
  - canon/story-concept.md
  - canon/story-arc.md
  - canon/world/world-rules.md
  - canon/relationships.yaml

agents:
  lead_editor:
    model: claude-haiku
    active: true
  plot_analyst:
    model: claude-haiku
    active: true
  depth_partner:
    model: claude-haiku
    active: true
  character_specialist:
    model: claude-haiku
    active: true
  continuity_agent:
    model: claude-haiku
    active: true
    tool_use: true
  prose_crafter:
    model: claude-haiku
    active: false

nodes: {}

mob_config:
  max_rounds: 3
  budget_cap_usd: 1.0
  diminishing_return_threshold: 0
